spring.application.name=RestaurantManagment

<<<<<<< HEAD
server.port=8002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/flmfoods
=======
server.port=9000
spring.datasource.DriverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/microservices
>>>>>>> 326af41dc2bec0cf38eb32d43beb7e6256d56af2
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true